<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gestion.Citas.Common\Gestion.Citas.Common.csproj" />
    <ProjectReference Include="..\Gestion.Citas.DataAccess\Gestion.Citas.DataAccess.csproj" />
  </ItemGroup>

</Project>
